services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-concept-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge