import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/organisms/header";
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased font-[family-name:var(--font-montserrat)]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
